version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          - REPO_NAME=miyucy/herokuishm
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t "${REPO_NAME}:latest" -t "${REPO_NAME}:${CIRCLE_SHA1}" .
          cat <(printf "FROM %s\n" "${REPO_NAME}:${CIRCLE_SHA1}") Dockerfile.test.t > Dockerfile.test
          docker build -t "${REPO_NAME}:test" -f Dockerfile.test .
          docker run --rm "${REPO_NAME}:test"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push "${REPO_NAME}:latest"
              docker push "${REPO_NAME}:${CIRCLE_SHA1}"
            fi
