version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          - REPO_NAME=miyucy/herokuishm
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker pull heroku/heroku:18-build
          docker pull heroku/heroku:18
      - run: |
          docker build -t "${REPO_NAME}:latest-build" -t "${REPO_NAME}:${CIRCLE_SHA1}-build" -f Dockerfile.build .
      - run: |
          docker build -t "${REPO_NAME}:latest" -t "${REPO_NAME}:${CIRCLE_SHA1}" -f Dockerfile .
      - run: |
          cat Dockerfile.test.t | sed -e "s|<REPO_NAME>|${REPO_NAME}|g" | sed -e "s|<CIRCLE_SHA1>|${CIRCLE_SHA1}|g" > Dockerfile.test
          docker build -t "${REPO_NAME}:test" -f Dockerfile.test .
          docker run -e PORT=5959 -e USER=herokuishuser "${REPO_NAME}:test"
      - deploy:
          command: |
            TAG_NAME=$(date -u '+%Y%m%d%H%M%S')
            docker tag "${REPO_NAME}:latest" "${REPO_NAME}:${TAG_NAME}"
            docker tag "${REPO_NAME}:latest-build" "${REPO_NAME}:${TAG_NAME}-build"
            docker images "${REPO_NAME}"
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push "${REPO_NAME}:latest"
              docker push "${REPO_NAME}:${TAG_NAME}"
              docker push "${REPO_NAME}:latest-build"
              docker push "${REPO_NAME}:${TAG_NAME}-build"
            fi
