version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          - REPO_NAME=miyucy/herokuishm
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker pull heroku/heroku:16
          docker pull heroku/heroku:16-build
      - run: |
          docker build -t "${REPO_NAME}:latest-build" -t "${REPO_NAME}:${CIRCLE_SHA1}-build" -f Dockerfile.build .
          f=$(mktemp)
          printf "FROM %s\n" "${REPO_NAME}:${CIRCLE_SHA1}-build" >> "${f}"
          cat Dockerfile.buildtest.t >> "${f}"
          mv "${f}" Dockerfile.buildtest
          docker build -t "${REPO_NAME}:buildtest" -f Dockerfile.buildtest .
          docker run -d --name buildtest "${REPO_NAME}:buildtest" /bin/bash
          docker cp -L buildtest:/tmp/slug.tgz .
          ls -al slug.tgz # tar tf slug.tgz
      - run: |
          docker build -t "${REPO_NAME}:latest" -t "${REPO_NAME}:${CIRCLE_SHA1}" -f Dockerfile .
          f=$(mktemp)
          printf "FROM %s\n" "${REPO_NAME}:${CIRCLE_SHA1}" >> "${f}"
          cat Dockerfile.test.t >> "${f}"
          mv "${f}" Dockerfile.test
          docker build -t "${REPO_NAME}:test" -f Dockerfile.test .
          docker run -e PORT=5959 -e USER=herokuishuser "${REPO_NAME}:test"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push "${REPO_NAME}:latest"
              docker push "${REPO_NAME}:${CIRCLE_SHA1}"
              docker push "${REPO_NAME}:latest-build"
              docker push "${REPO_NAME}:${CIRCLE_SHA1}-build"
            fi
